name: Deploy Hub (Update)

on:
  workflow_dispatch:
  workflow_call:
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: hub
          path: hub
          submodules: true
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: "^1.22.0"
          cache-dependency-path: |
            hub/go.sum

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.145.0"
          extended: true

      - name: Build Github
        run: |
          cd hub
          hugo --minify

      - name: Deploy to organization repo
        uses: crazy-max/ghaction-github-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT_LYRA }}
        with:
          repo: DoL-Lyra/hub
          build_dir: ./hub/public
          keep_history: false
          target_branch: pages
