name: Deploy Hub

on:
  # push:
  #   branches:
  #     - hub
  #   paths:
  #     - '.github/workflows/hub.yaml'
  workflow_dispatch:
  workflow_call:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: hub
          path: hub
          submodules: true
          fetch-depth: 0

      - uses: actions/download-artifact@v3
        with:
          name: pairs
          path: hub/pairs

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r hub/requirements.txt

      - name: Generate posts
        run: |
          cd hub
          python gen-comb.py ${{ github.ref_name }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Build
        run: |
          cd hub
          hugo --minify

      - name: Deploy to organization repo
        uses: crazy-max/ghaction-github-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
        with:
          repo: DOL-CHS-MODS/hub
          build_dir: ./hub/public
          keep_history: true
          target_branch: pages