name: Build Trigger

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  build_matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        version: [zip, apk]
        mod: [1,3]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'

      - id: getRelease
        name: release-downloader
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "Eltirosto/Degrees-of-Lewdity-Chinese-Localization"
          latest: true
          fileName: "*.${{ matrix.version }}"

      - name: Run mod script
        run: |
          echo ${{ secrets.SIGNING_KEY }} > dol.base64
          base64 -d dol.base64 > dol.jks
          ./mod.sh ${{ matrix.version }} ${{ matrix.mod }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dol-chs-mods
          path: output/*

  release:
    runs-on: ubuntu-latest
    needs: build_matrix
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: dol-chs-mods
          path: outputs
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: outputs