name: Build Trigger

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  build_matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        version: [zip, apk]
        mod: [1,3]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'

      - id: getRelease
        name: release-downloader
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "Eltirosto/Degrees-of-Lewdity-Chinese-Localization"
          latest: true
          fileName: "*.${{ matrix.version }}"

      - name: Run mod script
        run: |
          echo ${{ secrets.SIGNING_KEY }} > dol.base64
          base64 -d dol.base64 > dol.jks
          ./mod.sh ${{ matrix.version }} ${{ matrix.mod }} #${{ github.ref }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dol-chs-mods
          path: output/*

  release:
    runs-on: ubuntu-latest
    needs: build_matrix
    if: github.ref_type == 'tag'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: dol-chs-mods
          path: outputs
      # - name: Display structure of downloaded files
      #   run: ls -R
      #   working-directory: outputs
      - name: Generate release body
        id: gen_release_note
        run: |
          BASEURL=https://github.com/sakarie9/DOL-CHS-MODS/releases/download/${{ github.ref_name }}
          md=$(cat << EOF
          |     | 美化           | 美化+作弊     |
          |-----|----------------|---------------|
          | apk |  [下载]($BASEURL/$(cat outputs/apk_1)) | [下载]($BASEURL/$(cat outputs/apk_3)) |
          | zip |  [下载]($BASEURL/$(cat outputs/zip_1)) | [下载]($BASEURL/$(cat outputs/zip_3)) |
          EOF
          )
          md="${md//'%'/'%25'}"                               # Multiline escape sequences for %
          md="${md//$'\n'/'%0A'}"                             # Multiline escape sequences for '\n'
          md="${md//$'\r'/'%0D'}"                             # Multiline escape sequences for '\r'
          echo "RELEASE_BODY=$md" >> $GITHUB_OUTPUT

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: outputs/{*.zip,*.apk}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          prerelease: true
          body: |
            ${{ steps.gen_release_note.outputs.RELEASE_BODY }}