name: Trigger

on:
  workflow_dispatch:
    inputs:
      skip_DoLModLoaderBuild:
        description: "yes to skip DoLModLoaderBuild"
        required: false

env:
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}

jobs:
  check_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: run script
        run: |
          ORIGIN_TAG=$(curl -s https://api.github.com/repos/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/releases/latest | jq -r '.tag_name')
          CHS_VER=$(echo $ORIGIN_TAG | cut -d '-' -f3)
          MODS_VER=$(git tag --sort=-v:refname | head -n 1 | cut -d '-' -f2)

          if [[ "$CHS_VER" != "$MODS_VER" ]]
          then
            echo "Update needed"
            echo "NEED_UPDATE=true" >> "$GITHUB_ENV"

            NEW_VER="${ORIGIN_TAG//'chs-'/}"
            DATE=$(date -d "+8 hours" +%m%d)
            NEW_TAG=${NEW_VER}-${DATE}

            echo $NEW_TAG
            echo "NEW_TAG=$NEW_TAG" >> "$GITHUB_ENV"
          else
            echo "Already updated"
            echo "NEED_UPDATE=false" >> "$GITHUB_ENV"
          fi

      - name: Trigger DoL-Lyra/DoLModLoaderBuild/Update-Submodules.yaml
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        if: env.NEED_UPDATE == 'true' && inputs.skip_DoLModLoaderBuild != 'yes'
        with:
          owner: DoL-Lyra
          repo: DoLModLoaderBuild
          ref: master
          workflow_file_name: Update-Submodules.yaml
          github_token: ${{ secrets.GH_PAT_LYRA }}

      - name: Trigger DoL-Lyra/DoLModLoaderBuild/Build-Html-Package.yml
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        if: env.NEED_UPDATE == 'true' && inputs.skip_DoLModLoaderBuild != 'yes'
        with:
          owner: DoL-Lyra
          repo: DoLModLoaderBuild
          ref: master
          workflow_file_name: Build-Html-Package.yml
          github_token: ${{ secrets.GH_PAT_LYRA }}

      - name: Create tag
        if: env.NEED_UPDATE == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_TAG }}
          draft: true
