name: Trigger

on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hour
    - cron: '0 * * * 5' # every hour at friday
  workflow_dispatch:

env:
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}

jobs:
  check_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: run script
        run: |
          ORIGIN_TAG=$(curl -s https://api.github.com/repos/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/releases/latest | jq -r '.tag_name')
          CHS_VER=$(echo $ORIGIN_TAG | cut -d '-' -f3)
          MODS_VER=$(git tag --sort=-creatordate | grep -v 'we' | head -n 1 | cut -d '-' -f2)

          if [[ "$CHS_VER" != "$MODS_VER" ]]
          then
            echo "Update needed"
            echo "NEED_UPDATE=true" >> "$GITHUB_ENV"

            NEW_VER="${ORIGIN_TAG//'chs-'/}"
            DATE=$(date -d "+8 hours" +%m%d)
            NEW_TAG=${NEW_VER}-${DATE}

            echo $NEW_TAG
            echo "NEW_TAG=$NEW_TAG" >> "$GITHUB_ENV"
          else
            echo "Already updated"
            echo "NEED_UPDATE=false" >> "$GITHUB_ENV"
          fi

      - name: create empty commit
        if: env.NEED_UPDATE == 'true'
        run: |
          git config --global user.name $GIT_USERNAME
          git config --global user.email $GIT_EMAIL
          git commit --allow-empty -m "CI: new update"
          git push

      - name: create tag
        if: env.NEED_UPDATE == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_TAG }}
          draft: true

  check_update_we:
    runs-on: ubuntu-latest
    needs: check_update
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: run script
        run: |
          ORIGIN_TAG=$(curl -s https://api.github.com/repos/Eltirosto/Degrees-of-Lewdity-World-Expansion-Chinese-Localization/releases/latest | jq -r '.tag_name')
          CHS_WE_VER=$(echo $ORIGIN_TAG | cut -d '-' -f4)

          MODS_WE_VER=$(git tag --sort=-creatordate | grep 'we' | head -n 1 | cut -d '-' -f3)

          if [[ "$CHS_WE_VER" != "$MODS_WE_VER" ]]
          then
            echo "Update needed"
            echo "NEED_UPDATE=true" >> "$GITHUB_ENV"

            NEW_VER="${ORIGIN_TAG//'chs-'/}"
            DATE=$(date -d "+8 hours" +%m%d)
            NEW_TAG=${NEW_VER}-${DATE}

            echo $NEW_TAG
            echo "NEW_TAG=$NEW_TAG" >> "$GITHUB_ENV"
          else
            echo "Already updated"
            echo "NEED_UPDATE=false" >> "$GITHUB_ENV"
          fi

      - name: create empty commit
        if: env.NEED_UPDATE == 'true'
        run: |
          git config --global user.name $GIT_USERNAME
          git config --global user.email $GIT_EMAIL
          git commit --allow-empty -m "CI: new we update"
          git push

      - name: create tag
        if: env.NEED_UPDATE == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_TAG }}
          draft: true
